### ISSUE TITLE
Send to buttons still don't work with all recent updates and merges

### ISSUE THREAD

**Issue by opy188** [yfszzx/stable-diffusion-webui-images-browser#30]
As said, I load a page for the image browser, and all "send to" buttons vanish, unable to do anything. I just fresh installed the extension and updated the webui, so I have no idea what's going on.

**Comment by ArchGroot** [comment]
> 

same thing, plus no "Generate Info" and "File name" outputs
![0ecf2876cac54f16a3de0ac46d7b5214](https://user-images.githubusercontent.com/116215982/199068719-6f5b0f01-8670-4f8f-bce9-c3caac1b487b.png)

**Comment by ResleyZ** [comment]
I've found a solution, if you delete the Extension folder, and reinstall it from the WebUI, it will work perfectly fine.

I've tested this with several extensions, and after deleting them, reinstalling through the WebUI, and applying and reinstalling it as well brings back all the functionalities.

**Comment by opy188** [comment]
mine just keeps saying Namespace' object has no attribute 'disable_extension_access when I try installing through the webui

**Comment by ResleyZ** [comment]
> 

If you have --listen or --share as a CMD argument, you'll need to remove that. Without that it should work, and you could enable it again afterwards.

**Comment by opy188** [comment]
I have nothing enabled like that. Launched without any arguments though and it's pursued. I have found the line in the UI extensions python file that seems to be set up to prevent this. So I guess I could mess around with this and see if that fixes it

**Comment by opy188** [comment]
This is the code. What should i change this to to allow these dang extensions.
![testing](https://user-images.githubusercontent.com/43479833/199104095-91316515-03aa-47b4-87e9-59f4a2350ff8.png)

**Comment by opy188** [comment]
okay i think i fixed it. There was a recent update that adjusted the mentioned line

**Comment by opy188** [comment]
i lied, still doesn't work. in fact installing it through the webui does nothing, and now there is no image browser tab at all

**Comment by ResleyZ** [comment]
I had did these steps;
Delete the current folder from the Extensions folder
From within the UI, go to the Extension Tab > Install from URL tab, and paste in https://github.com/yfszzx/stable-diffusion-webui-images-browser
Leave the "Local directory name" empty
Press "Install"
From the "Installed tab, press Apply and Restart UI"

**Comment by opy188** [comment]
god bless you. though my primary issue was there was a secret installation of the folder in my tmp folder. And I had to delete that. Now it works and every is now fine. Appreciate it

**Comment by opy188** [comment]
The issue remains unsolved. If you fix it with the mentioned method above, it breaks again with a restart. This fix seems to need something fundamentally adjusted in the extension

**Comment by digital-soul18** [comment]
Yep, not working for me either. When I try and install the extension I get this error

GitCommandError: Cmd('git') failed due to: exit code(128)
cmdline: git clone -v https://github.com/yfszzx/stable-diffusion-webui-images-browser /content/gdrive/MyDrive/sd/stable-diffusion-webui/tmp/stable-diffusion-webui-images-browser
stderr: 'Cloning into '/content/gdrive/MyDrive/sd/stable-diffusion-webui/tmp/stable-diffusion-webui-images-browser'...
fatal: I don't handle protocol ' https'

**Comment by albusgod** [comment]
fresh install, my work fine, it display the info but there is no buttons to send to text2img or send to img2img

**Comment by digital-soul18** [comment]
Yes exactly, my buttons don't work either, everything else was fine.

**Comment by dhwz** [comment]
No fix, but just a temporary solution so you get a working images-browser again:

Go to your stable-diffusion-webui folder and do:
```git checkout -b old-state f87dcf1ad8722674bf4c84b0f992070af223fb7d```
This will jump back 2 days to a working state of the webui

**Comment by ArchGroot** [comment]
I erased all extension from extension folder, disabled cmd args from webui-user.bat --listen and --port (because webui won't let you change extensions), restarted sd with git pull into webui-user.bat, to have the latest update, and installed the new extensions 
![image](https://user-images.githubusercontent.com/116215982/199304906-07666401-b7ed-4302-ae38-e3928d9f9cae.png)
And voila, the results, generation info and the buttons are there:
![image](https://user-images.githubusercontent.com/116215982/199305066-1208ab71-af8b-4981-b5da-16ff777b617f.png)

**Comment by MrKuenning** [comment]
I can confirm that removing the Image Browser extension, clearing all of my arguments, and reinstalling the extension from the WebUI did restore the buttons.  However, as soon as I put my arguments back in the buttons disappeared.  Additionally removing all of them again does not bring them back.

The arguments I am currently using are:

--listen 
--deepdanbooru 
--disable-safe-unpickle 
--styles-file
--administrator 
--port
--gradio-auth

I am curious if this issue is related to this PR 
https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/3768
"Create all “send to“ button in one module"

**Comment by dhwz** [comment]
Yes it doesn't work right now, webui needs to be fixed first, roll back like I described above if you don't want to wait.

**Comment by judgeou** [comment]
> > 
> 
> If you have --listen or --share as a CMD argument, you'll need to remove that. Without that it should work, and you could enable it again afterwards.

Honestly, it's a stupid design.

**Comment by judgeou** [comment]
just back to 3a8807aa7e59e607c8c0f90fe52eef6e842adca0 works

<img width="1358" alt="image" src="https://user-images.githubusercontent.com/2416816/199394868-576822f8-b3bc-4caa-af70-3958c056b9fd.png">

**Comment by MrKuenning** [comment]
Confirmed working again, with no roll backs or tweaks.

**Comment by yfszzx** [comment]
done

**Comment by digital-soul18** [comment]
It still isn't working for me despite deleting the plugin and restarting.

**Comment by yfszzx** [comment]
> It still isn't working for me despite deleting the plugin and restarting.

git pull "webui" and "images browser"

**Comment by digital-soul18** [comment]
I do have the latest versions of these. Could it be because I am using fast stable diffusion?
https://github.com/TheLastBen/fast-stable-diffusion

That may overwrite webui but I'm not sure.
